[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
photon = "3cAFEXstVzff2dXH8PFMgm81h8sQgpdskFGZqqoDgQkJ"
onefunc = "EjpcUpcuJV2Mq9vjELMZHhgpvJ4ggoWtUYCTFqw6D9CZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
propose = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'propose' tests/photon.ts"
byname = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'executeOperation by name' tests/photon.ts"
bycode = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'executeOperation by code' tests/photon.ts"

[test]
startup_wait = 10000
