[toolchain]

[features]
seeds = false
skip-lint = false
default = []

[programs.localnet]
photon = "JDxWYX5NrL51oPcYunS7ssmikkqMLcuHn9v4HRnedKHT"
onefunc = "EjpcUpcuJV2Mq9vjELMZHhgpvJ4ggoWtUYCTFqw6D9CZ"

[programs.mainnet]
photon = "pccm961CjaR7T7Hcht9omrXQb9w54ntJo95FFT7N9AJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
propose = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'propose' tests/photon.ts"
byname = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'executeOperation by name' tests/photon.ts"
bycode = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 -g 'executeOperation by code' tests/photon.ts"

[test]
startup_wait = 10000
