rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: to_solana
    consumer_tag: solana
    queue: "signed_operations"
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    web_socket_url: ws://solana:8900
    rpc_url: http://solana:8899
    commitment: finalized

# List of executor extensions registered for solana transaction preprocessing
extensions:
  - /libonefunc_extension.so
