rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: to_solana
    consumer_tag: solana
    queue: "to_solana"
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    rpc_url: https://wandering-icy-road.solana-mainnet.quiknode.pro/914f9b67832d4cdde6b801a8e0987814799a4f52
    commitment: confirmed

extensions:
    - /libonefunc_extension.so
    - /libgov_extension.so
    - /libbridge_extension.so
    - /libborpa_bridge_extension.so

mongodb:
    uri: mongodb://mongo:27017
    user: root
    db: "entangle"
    key: "last_processed_block"
