rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: to_solana
    consumer_tag: solana
    queue: "to_solana"
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    rpc_url: https://api.mainnet-beta.solana.com
    commitment: confirmed

extensions:
    - /libonefunc_extension.so
    - /libgov_extension.so
    - /libbridge_extension.so

mongodb:
    uri: mongodb://mongo:27017
    user: root
    db: "entangle"
    key: "last_processed_block"
