rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: to_solana
    consumer_tag: solana
    queue: "to_solana"
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    web_socket_url: wss://rpc.ankr.com/solana/ws/bd53c71861ec986f1d40e84d82d327d181fb61c6057f5fbb4fd01c93d6389c97
    rpc_url: https://rpc.ankr.com/solana/bd53c71861ec986f1d40e84d82d327d181fb61c6057f5fbb4fd01c93d6389c97
    commitment: confirmed

extensions:
    - /libonefunc_extension.so
    - /libgov_extension.so
    - /libbridge_extension.so

mongodb:
    uri: mongodb://mongo:27017
    user: root
    db: "entangle"
    key: "last_processed_block"
