rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: to_solana
    consumer_tag: solana
    queue: "to_solana"
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    rpc_url: https://rpc.ankr.com/solana/b2717015880533388be8430381f5b7aa3cf67478932e878e19166a418495759b
    commitment: confirmed

extensions:
    - /libonefunc_extension.so
    - /libgov_extension.so
    - /libbridge_extension.so

mongodb:
    uri: mongodb://mongo:27017
    user: root
    db: "entangle"
    key: "last_processed_block"
