rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: from_solana
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    web_socket_url: wss://https://api.mainnet-beta.solana.com
    rpc_url: https://api.mainnet-beta.solana.com
    commitment: finalized
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

mongodb:
    uri: mongodb://mongo:27017
    db: "entangle"
    key: "last_processed_block"
