rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: from_solana
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    rpc_url: https://rpc.ankr.com/solana/b2717015880533388be8430381f5b7aa3cf67478932e878e19166a418495759b
    commitment: finalized

mongodb:
    uri: mongodb://mongo:27017
    db: "entangle"
    key: "last_processed_block"

allowed_protocols:
    - "photon-gov"
    - "Entangle"
