rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: from_solana
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    read_rpcs:
        - url: https://wandering-icy-road.solana-mainnet.quiknode.pro/914f9b67832d4cdde6b801a8e0987814799a4f52
          ratelimit: 4
    write_rpcs:
        - url: https://wandering-icy-road.solana-mainnet.quiknode.pro/914f9b67832d4cdde6b801a8e0987814799a4f52
          ratelimit: 1
    commitment: finalized

mongodb:
    uri: mongodb://mongo:27017
    db: "entangle"
    key: "last_watched_block"
