rabbitmq:
    host: rabbitmq
    port: 5672
    exchange: entangle
    routing_key: from_solana
    reconnect_attempts: 100
    reconnect_timeout_ms: 200

solana:
    read_rpcs:
        -   url: http://solana:8899
            ratelimit: 4
    write_rpcs:
        -   url: http://solana:8899
            ratelimit: 1
    commitment: finalized

mongodb:
    uri: mongodb://mongo:27017
    db: "entangle"
    key: "last_watched_block"
