# rabbit AMQP 0.9.1 settings to connect with and establish a channel
rabbitmq:
    # The server host
    host: localhost
    # The server port. Default: 5672 by [AMQP 0-9-1 spec](https://www.rabbitmq.com/amqp-0-9-1-reference.html).
    port: 5672
    # Exchange name
    exchange: entangle
    # Routing key
    routing_key: from_solana
    # Reconnect attempts. The count of times listener will try to recover the connection. Default: 20
    reconnect_attempts: 100
    # Reconnect Timeout. The time between attempts for the listener to try to reconnect. Default: 500
    reconnect_timeout_ms: 200

# solana [pubsubclient](https://docs.rs/solana-pubsub-client/latest/solana_pubsub_client/nonblocking/pubsub_client/index.html) settings
solana:
    # HTTP RPC addresses to connect to read and write to Solana
    read_rpcs:
        -   url: http://127.0.0.1:8899
            ratelimit: 4 # requests per second
    write_rpcs:
        -   url: http://127.0.0.1:8899
            ratelimit: 4 # requests per second
    # The solana client commitment receive only events have been happened on the given confirmation level
    # possible values: processed, confirmed, finalized
    commitment: confirmed
    tx_read_from: 4XLh37MiWEYvVGQomQm7Qx3PqX8HHENe1ndhM8ANSUZE6L7ASQE2uphme3d2ew2Vk8c4Jtjq3beFoLycH84mweEK

# mongodb is used to store last_processed_block in a persistent way
mongodb:
    # Mongodb uri to connect to
    uri: mongodb://127.0.0.1:27017
    # Mongodb user name
    user: root
    # Mongodb user password
    password: rootpassword
    # Database that is used to get last_processed_block during the retrospective proposal reading
    db: "entangle"
    # The value to read until within the retrospective reading
    key: "last_watched_block"
