# rabbit AMQP 0.9.1 settings to connect with and establish a channel
rabbitmq:
    # The server host
    host: localhost
    # The server port. Default: 5672 by [AMQP 0-9-1 spec](https://www.rabbitmq.com/amqp-0-9-1-reference.html).
    port: 5672
    # Exchange name
    exchange: entangle
    # Routing key
    routing_key: solana

# solana [pubsubclient](https://docs.rs/solana-pubsub-client/latest/solana_pubsub_client/nonblocking/pubsub_client/index.html) settings
solana:
    # solana web socket address to connect to handle entangle events
    web_socket_url: ws://127.0.0.1:8900
    # possible values: processed, confirmed, finalized
    commitment: confirmed
    # 16 byte number that used to address source chain_id
    chain_id: 6546541123432511133111030303
